---
title: "01_Data"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("readxl")) {
  install.packages("readxl")
  require("readxl")
}
if (!require("stringr")) {
  install.packages("stringr")
  require("stringr")
}
```

# Folder for the output
```{r eval=FALSE}
dir.create("01_Output")
```

# First, the master database with suicide attempts over the year
```{r master data}
# Raw data in separate tabs
path <- "~/Labs/Github/Project_life_force/Project_Life_Force/Raw_datasets/database_12-29-2024.xlsx"
excel_sheets(path)

# This tab has suicide attempt data
events <- read_excel(path, sheet = "events")

# This tab has more attempt info
statusdat <- read_excel(path, sheet = "status")

events$dtdied <- statusdat$dtdied[match(events$id, statusdat$id)]
```

# Baseline C-SSRS data (lifetime and recent)
```{r cssrs data}
# Import C-SSRS data
cssrs_labels <- read.csv("~/Labs/Github/Project_life_force/Project_Life_Force/Raw_datasets/CSSRS_Baseline_Recent_Labels.csv")
cssrs_raw <- read.csv("~/Labs/Github/Project_life_force/Project_Life_Force/Raw_datasets/CSSRS_Baseline_Recent_Raw.csv")

# Fix the IDs
cssrs_raw <- cssrs_raw %>%
  mutate(subject_id = case_when(
    str_detect(subject_id, "^(?i)pp\\d+") ~ str_replace(subject_id, "^(?i)pp(\\d+)", "PH-\\1"),
    str_detect(subject_id, "^(?i)pt1\\d+") ~ str_replace(subject_id, "^(?i)pt1(\\d+)", "TX-\\1"),
    str_detect(subject_id, "^(?i)pt\\d+") ~ str_replace(subject_id, "^(?i)pt(\\d+)", "TX-\\1"),
    str_detect(subject_id, "^(?i)pn\\d+") ~ str_replace(subject_id, "^(?i)pn(\\d+)", "NP-\\1"),
    str_detect(subject_id, "^(?i)p\\d+") ~ str_replace(subject_id, "^(?i)p(\\d+)", "BX-\\1"),
    TRUE ~ subject_id
  )) %>%
  rename(id = subject_id) # and rename the column

# Check how many IDs overlap with the ids in the events sheet (all, 207)
length(intersect(cssrs_raw$id, events$id))

# Filter the C-SSRS data to only IDs that are in events
cssrs_raw_filtered <- cssrs_raw %>%
  filter(id %in% events$id)

# Now, to make a recent and lifetime suicide attempt variables:
# 0 = No, 1 = yes.

# "cssrs_actattrec_bl" = Actual Attempt (Recent)
# "cssrs_intattrec_bl" = Interrupted Attempt (Recent)
# "cssrs_abtattrec_bl" = Aborted or Self-Interrupted Attempt (Recent)
# "cssrs_preprec_bl" = Preparatory Acts or Behavior (Recent)

# "cssrs_actattlt_bl" = Actual Attempt (Lifetime)
# "cssrs_intattlt_bl" = Interrupted Attempt (Lifetime)
# "cssrs_abtattlt_bl" = Aborted or Self-Interrupted Attempt (Lifetime)
# "cssrs_preplt_bl" = Preparatory Acts or Behavior (Recent)

# cssrs_sbrec_bl = "Was Suicidal Behavior present during the past year? (Recent)
# Note: Code yes if the subject answered yes to any of the behaviors in this section EXCEPT Non-suicidal Self-Injurious Behavior."

# "cssrs_sblt_bl" = "Was Suicidal Behavior present during the participant's lifetime?
# Note: Code yes if the subject answered yes to any of the behaviors in this section EXCEPT Non-suicidal Self-Injurious Behavior."

# Make "recent" and "lifetime" attempt variables from aborted, interrupted, and actual behaviors
# If they have ANY of them == 1
# If they have NONE of them == 0
# If they have a combination of NONE and MISSING == NA
cssrs_raw_filtered <- cssrs_raw_filtered %>%
  mutate(
    attempt_recent = case_when(
      rowSums(across(c(
        cssrs_actattrec_bl,
        cssrs_intattrec_bl,
        cssrs_abtattrec_bl
      ), ~ . == 1), na.rm = TRUE) > 0 ~ 1,
      rowSums(across(c(
        cssrs_actattrec_bl,
        cssrs_intattrec_bl,
        cssrs_abtattrec_bl
      ), ~ . == 0), na.rm = FALSE) == 3 ~ 0,
      TRUE ~ NA_real_
    ),
    attempt_lifetime = case_when(
      rowSums(across(c(
        cssrs_actattlt_bl,
        cssrs_intattlt_bl,
        cssrs_abtattlt_bl
      ), ~ . == 1), na.rm = TRUE) > 0 ~ 1,
      rowSums(across(c(
        cssrs_actattlt_bl,
        cssrs_intattlt_bl,
        cssrs_abtattlt_bl
      ), ~ . == 0), na.rm = FALSE) == 3 ~ 0,
      TRUE ~ NA_real_
    )
  )

# Add the lifetime variable into the suicide attempt data sheet
events$attempt_lifetime <- cssrs_raw_filtered$attempt_lifetime[match(events$id, cssrs_raw_filtered$id)]

# Add the recent variable into the suicide attempt data sheet
events$attempt_recent <- cssrs_raw_filtered$attempt_recent[match(events$id, cssrs_raw_filtered$id)]

table(events_filtered$attempt_recent)
# 59 vs 67
```

# Baseline report
```{r events}
# Self-report data for all participants at all waves
plf_data <- read.csv("~/Labs/Github/Project_life_force/Project_Life_Force/01_Created_datasets/Merged_plf_data_filtered_2025-04-09.csv")

# Add baseline self-report variables to the suicide attempt data (events)

# First, filter the PLF data to just baseline
plf_data_baseline <- plf_data %>%
  filter(
    month == 0
  )

# Make a new BHS sum score for validity
bhs_items <- plf_data_baseline %>% select(ends_with("_bhs")) # Select all BHS items
plf_data_baseline$bhs_new <- rowSums(bhs_items, na.rm = FALSE) # Sum all BHS items

# Make sure that the new sum score is the same as the original
summary(plf_data_baseline$bhs)
summary(plf_data_baseline$bhs_new)


# Make BHS subscales from negative expectation items and positive expectation items

# Currently, the positive expectation items are reverse scored so that endorsing a positive expectation  = 0
# Reverse these back to the original scoring so that endorsing the positive expectation = 1
# Then sum the new posiitive expectation items for a total score
plf_data_baseline <- plf_data_baseline %>%
  mutate(
    q01_bhs_r = 1 - q01_bhs,
    q03_bhs_r = 1 - q03_bhs,
    q05_bhs_r = 1 - q05_bhs,
    q06_bhs_r = 1 - q06_bhs,
    q08_bhs_r = 1 - q08_bhs,
    q10_bhs_r = 1 - q10_bhs,
    q13_bhs_r = 1 - q13_bhs,
    q15_bhs_r = 1 - q15_bhs,
    q19_bhs_r = 1 - q19_bhs
  ) %>%
  mutate(
    bhs_pos = rowSums(select(
      ., q01_bhs_r, q03_bhs_r, q05_bhs_r, q06_bhs_r,
      q08_bhs_r, q10_bhs_r, q13_bhs_r, q15_bhs_r, q19_bhs_r
    ), na.rm = FALSE)
  ) %>%
  mutate(
    bhs_pos_n = rowSums(select(
      ., q01_bhs, q03_bhs, q05_bhs, q06_bhs,
      q08_bhs, q10_bhs, q13_bhs, q15_bhs, q19_bhs
    ), na.rm = FALSE)
  )

# Verify the reverse scoring
table(plf_data_baseline$q01_bhs)
table(plf_data_baseline$q01_bhs_r) # Good

table(plf_data_baseline$bhs_pos_n)
table(plf_data_baseline$bhs_pos) # Good

# Make the negative expectation subscale
plf_data_baseline <- plf_data_baseline %>%
  mutate(
    bhs_neg = rowSums(across(
      c(
        q02_bhs, q04_bhs, q07_bhs, q09_bhs, q11_bhs, q12_bhs,
        q14_bhs, q16_bhs, q17_bhs, q18_bhs, q20_bhs
      ),
      ~ as.numeric(.)
    ), na.rm = FALSE)
  )

# From this dataset, add variables to the events dataset
# Treatment condition
events$arm_rec <- plf_data_baseline$arm_rec[match(events$id, plf_data_baseline$id)]

# BHS scores (total, negative expectations, and positive expectations)
events$bhs <- plf_data_baseline$bhs[match(events$id, plf_data_baseline$id)]
events$bhs_pos <- plf_data_baseline$bhs_pos[match(events$id, plf_data_baseline$id)]
events$bhs_neg <- plf_data_baseline$bhs_neg[match(events$id, plf_data_baseline$id)]

# Scale for Suicidal Ideation items:
## suicidal ideation (item 6)
events$q06_ssi <- plf_data_baseline$q06_ssi[match(events$id, plf_data_baseline$id)]

## suicidal expectation (item 15)
events$q15_ssi <- plf_data_baseline$q15_ssi[match(events$id, plf_data_baseline$id)]

## suicide method/opportunity access
events$q13_ssi <- plf_data_baseline$q13_ssi[match(events$id, plf_data_baseline$id)]

## suicide preparation
events$q16_ssi <- plf_data_baseline$q16_ssi[match(events$id, plf_data_baseline$id)]

# Perceived suicide-related coping scale
events$srcs17 <- plf_data_baseline$srcs17[match(events$id, plf_data_baseline$id)]
events$isi <- plf_data_baseline$isi[match(events$id, plf_data_baseline$id)]

# Demographics
events$age_demo <- plf_data_baseline$age_demo[match(events$id, plf_data_baseline$id)]
events$sex_demo <- plf_data_baseline$sex_demo[match(events$id, plf_data_baseline$id)]
events$race_demo <- plf_data_baseline$race_demo[match(events$id, plf_data_baseline$id)]
events$latino_demo <- plf_data_baseline$latino_demo[match(events$id, plf_data_baseline$id)]
events$degree_demo <- plf_data_baseline$degree_demo[match(events$id, plf_data_baseline$id)]
events$employ_demo <- plf_data_baseline$employ_demo[match(events$id, plf_data_baseline$id)]
events$marry_demo <- plf_data_baseline$marry_demo[match(events$id, plf_data_baseline$id)]
events$prison_demo <- plf_data_baseline$prison_demo[match(events$id, plf_data_baseline$id)]
events$prior_demo <- plf_data_baseline$prior_demo[match(events$id, plf_data_baseline$id)]

# Major Depressive Episode info from the MINI
events$when01p_mini <- plf_data_baseline$when01p_mini[match(events$id, plf_data_baseline$id)] # Past MDE
events$when01c_mini <- plf_data_baseline$when01c_mini[match(events$id, plf_data_baseline$id)] # Current MDE
events$when01r_mini <- plf_data_baseline$when01r_mini[match(events$id, plf_data_baseline$id)] # Recurrent MDE
```

# Filter the dataset for analysis
```{r filter}
# Filter to those who have Beck Scale for Suicidal Ideation item 15 (expectation of a future suicide attempt)
events_filtered <- events %>%
  filter(!is.na(q15_ssi))

# Filter to people who aren't missing the C-SSRS
events_filtered <- events_filtered %>%
  filter(!is.na(cssrs_actattlt_bl))

# Look at MDE information
table(events_filtered$when01p_mini) # Past
table(events_filtered$when01r_mini) # Recurrent
table(events_filtered$when01c_mini) # Current

# Does everyone have a past, recurrent, or current MDE?
sum(
  events_filtered$when01c_mini == 0 &
    events_filtered$when01r_mini == 0 &
    events_filtered$when01p_mini == 0,
  na.rm = TRUE
) # Everyone had past (74), current (106), or recurrent (85) depression (but 10 people missing the MINI)
```

# Make new variables for analysis
```{r new vars}
# BHS dichotomous variable; 9 and over = 1.
events_filtered <- events_filtered %>%
  mutate(bhs_9 = case_when(
    is.na(bhs) ~ NA_integer_,
    bhs >= 9 ~ 1,
    bhs < 9 ~ 0
  ))

table(events_filtered$bhs_9)

# Item 15 (Expectation for suicide)
# Collapse 0 (no) and 1 (unsure) vs. 2 (sure)
events_filtered$q15_ssi_2 <- ifelse(events_filtered$q15_ssi == 2, 1, 0)

table(events_filtered$q15_ssi_2)
table(events_filtered$q15_ssi)

# Item 16 (preparation for suicide)
# 0 (no preparation) vs. 1 (some preparation) and 2 (almost finished or completed preparation) collapsed
events_filtered$q16_ssi_2 <- ifelse(events_filtered$q16_ssi %in% c(1, 2), 1,
  ifelse(is.na(events_filtered$q13_ssi), NA, 0)
)

# Item 13 (perceived access to method/opportunity for suicide)
# No method + method/no opportunity vs. method and opportunity
events_filtered$q13_ssi_2 <- ifelse(events_filtered$q13_ssi == 2, 1,
  ifelse(is.na(events_filtered$q06_ssi), NA, 0)
)

table(events_filtered$q13_ssi)
table(events_filtered$q13_ssi_2)
```

# Truncate time-to-event to one year
```{r truncate time}
# Does anyone go past 365 days?
sum(events_filtered$surv > 365, na.rm = TRUE)

# Are any of the first attempts >365 days?
sum(events_filtered$att1 == 1 & events_filtered$surv > 365, na.rm = TRUE)

# Look at IDs of attempt #1 >365 days
events_filtered %>%
  filter(att1 == 1 & surv > 365) %>%
  pull(id) # BX-036

# Truncate time to 365 days
# For the the one person that had their first attempt >365 days, change their attempt code from 1 to 0
events_filtered <- events_filtered %>%
  mutate(
    surv_365 = pmin(surv, 365), # Truncate follow-up at 365 days
    att1_365 = ifelse(att1 == 1 & surv <= 365, 1, 0) # Only mark as event if it occurred within 365 days
  )

table(events_filtered$surv_365)

# surv_365 is the new variable for survival analysis, truncated at 365 days
# att1_365 is the new attempt variable, truncated at 365 days

# Verify that the 1 person goes from attempt -> no attempt
table(events_filtered$att1)
table(events_filtered$att1_365)

# Since this truncates at 365, the total number of attempts also needs to be checked (att1_365, att2, att3...)

# Truncate all attempts to 365 days
events_filtered <- events_filtered %>%
  mutate(
    att2_365 = ifelse(att2 == 1 & day2 <= 365, 1, 0),
    att3_365 = ifelse(att3 == 1 & day3 <= 365, 1, 0),
    att4_365 = ifelse(att4 == 1 & day4 <= 365, 1, 0),
    att5_365 = ifelse(att5 == 1 & day5 <= 365, 1, 0),
    att6_365 = ifelse(att6 == 1 & day6 <= 365, 1, 0),
    att7_365 = ifelse(att7 == 1 & day7 <= 365, 1, 0),
    att8_365 = ifelse(att8 == 1 & day8 <= 365, 1, 0)
  )

# Make a new total number of attempts variable
events_filtered <- events_filtered %>%
  mutate(
    natts_365 =
      att1_365
      + att2_365
        + att3_365
        + att4_365
        + att5_365
        + att6_365
        + att7_365
        + att8_365
  )

# Check the new numbers
table(events_filtered$natts)
table(events_filtered$natts_365) # One recurrent attempt was lost (and one emergent one from before)

# Make a dichotomous variable for number of attempts; >1 = 1 and 1 and under = 0
events_filtered$natts_di <- ifelse(events_filtered$natts_365 > 1, 1, 0)
table(events_filtered$natts_di)

# Make a dichotomous variable for 1 vs >1 attempts
events_filtered$natts_di_2 <- ifelse(is.na(events_filtered$natts_365), NA,
  ifelse(events_filtered$natts_365 == 0, NA,
    ifelse(events_filtered$natts_365 == 1, 0, 1)
  )
)

# Who had less than 365 days of tracking?
events_filtered %>%
  filter(surv < 364, att1_365 == 0, died == 0)

summary(events_filtered$surv[events_filtered$surv < 364 &
  events_filtered$att1_365 == 0 &
  events_filtered$died == 0])

table(events_filtered$surv[events_filtered$surv < 364 &
  events_filtered$att1_365 == 0 &
  events_filtered$died == 0])
```

# Make dataframes with participant death(s) removed
```{r dth data}
# Remove people who died with no emergent suicide attempt
events_filtered_1 <- events_filtered %>%
  filter(died != 1)

# Who was removed?
events_filtered %>%
  filter(died == 1) %>%
  pull(id)

# Remove people who died with and without an emergent suicide attempt
events_filtered_2 <- events_filtered %>%
  filter(is.na(dtdied))

# Who was removed?
events_filtered %>%
  filter(!is.na(dtdied)) %>%
  pull(id)

# Look at their data
events_filtered %>%
  filter(!is.na(dtdied))

# Remove participants who had less then 340 days available and no emergent suicide attempt
events_filtered_3 <- events_filtered_1 %>%
  filter(!(died != 1 & surv_365 < 340 & att1_365 == 0))

# Remove participants who had less then 365 days available and no emergent suicide attempt
events_filtered_4 <- events_filtered_1 %>%
  filter(!(died != 1 & surv_365 < 365 & att1_365 == 0))
```

# Save the dataset
```{r save}
write.csv(
  events_filtered,
  paste0("01_Output/Events_data_SG_", Sys.Date(), ".csv")
)
# 2025-06-15: First dataset
# 2025-05-20: Added BHS subscales (positive & negative expectations separately)
# 2025-07-22: Added perceived suicide-related coping
```

